name: Build and Deploy Bookdown

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'
        
    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2
      
    - name: Install R dependencies
      run: |
        install.packages(c("bookdown", "rmarkdown", "knitr"))
      shell: Rscript {0}
      
    - name: Build book
      run: |
        bookdown::render_book("index.Rmd", "bookdown::gitbook")
      shell: Rscript {0}
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book
